version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./JsonData:/app/JsonData
      - ./PdfData:/app/PdfData
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
    restart: unless-stopped
    # For Azure Container Instances compatibility
    platform: linux/amd64
